apiVersion: v1
kind: Secret
metadata:
  name: reverse-proxy
  labels:
type: Opaque
data:
{{- $root := . }}
{{- range $key, $value := .Values.serviceSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}