kind: helm-release
apiVersion: 1.1
build:
  context: ../../
  dockerfile: Dockerfile
install:
  chart: charts/tenant-manager
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: tenant-manager
      tag: $(tag)
      pullPolicy: Never
    ingress:
      # enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to form the service's public URL: [space.s.][rootSpace.]tenant-manager.<random suffix>.<region>.azds.io
      # Customize the public URL by changing the 'tenant-manager' text between the $(rootSpacePrefix) and $(hostSuffix) tokens
      # For more information see https://aka.ms/devspaces/routing
      - $(spacePrefix)$(rootSpacePrefix)tenant-manager$(hostSuffix)
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Debug}
        AppConfigurationConnectionString: ${secret.globalsecrets.AppConfigurationConnectionString}