
parameters:
  serviceConnection: ''
  resourceGroup: ''
  location: ''
  appConfigName: ''
  aksName: ''

steps:
- task: AzureResourceGroupDeployment@2
  displayName: "Deploy App Configuration"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: ${{ parameters.location }}
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/appconfig.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/appconfig.json'
    overrideParameters: '-appConfigName ${{ parameters.appConfigName }} -location ${{ parameters.location }}'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

- task: AzureCLI@1
  displayName: Create App Config Secret in Kube
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |-
      az aks get-credentials -n ${{ parameters.aksName }} -g ${{ parameters.resourceGroup }}
      connString=$(az appconfig credential list --name ${{ parameters.appConfigName }} -g ${{ parameters.resourceGroup }} | jq -r .[0].connectionString)
      kubectl create secret generic --namespace=default globalsecrets --from-literal=PCS_APPLICATION_CONFIGURATION=$connString --dry-run -o yaml | kubectl apply -f -

- task: AzureCLI@1
  displayName: Add Values to App Config
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |-
      # Needed because Azure Devops has a bug in the extention included, normally the extension will handle the flattening --  Andrew Schmidt
      jq --arg delim ':' 'reduce (tostream|select(length==2)) as $i ({};
          .[[$i[0][]|tostring]|join($delim)] = $i[1]
      )' $(System.DefaultWorkingDirectory)/deployment/pipelines/templates/infra/app-config-template.json > $(System.DefaultWorkingDirectory)/deployment/pipelines/templates/infra/app-config-template-translated.json 
      rg=${{ parameters.resourceGroup }}
      # app insight key
      appInsightName=$(az resource list -g $rg --resource-type "Microsoft.Insights/components" | grep name | grep appinsight | awk -F "\"" '{print $4}')
      appInsightKey=$(az resource show -g $rg -n $appInsightName --resource-type "Microsoft.Insights/components" --query properties.InstrumentationKey)
      appInsightKey="${appInsightKey//\"}"
      # cosmos db connection string
      cosmosDbAccountName=$(az cosmosdb list --resource-group $rg | grep name | awk -F "\"" '{print $4}')
      cosmosDbEndpoint="https://$cosmosDbAccountName.documents.azure.com:443/"
      cosmosDbAuthKey=$(az cosmosdb list-keys --resource-group $rg --name $cosmosDbAccountName | grep primaryMasterKey | awk -F "\"" '{print $4}')
      cosmosDbConnection="AccountEndpoint=$cosmosDbEndpoint;AccountKey=$cosmosDbAuthKey;"
      # event hub connection string
      evNamespace=$(az eventhubs namespace list --resource-group $rg| grep name| grep eventhub| cut -d "/" -f1| awk -F "\"" '{print $4}')
      ehQueueAuthRule='iothubroutes'
      lifecycleEv=$(az eventhubs eventhub list --resource-group $rg --namespace-name $evNamespace| grep name |grep lifecycle| awk -F "\"" '{print $4}'| cut -d "/" -f1)
      lifecycleEvConn=$(az eventhubs eventhub authorization-rule keys list --resource-group $rg --namespace-name $evNamespace --eventhub-name $lifecycleEv --name $ehQueueAuthRule |grep primaryConnectionString | awk -F "\"" '{print $4}')
      telemetryEv=$(az eventhubs eventhub list --resource-group $rg --namespace-name $evNamespace| grep name |grep telemetry| awk -F "\"" '{print $4}'| cut -d "/" -f1)
      telemetryEvConn=$(az eventhubs eventhub authorization-rule keys list --resource-group $rg --namespace-name $evNamespace --eventhub-name $telemetryEv --name $ehQueueAuthRule |grep primaryConnectionString | awk -F "\"" '{print $4}')
      twinchangeEv=$(az eventhubs eventhub list --resource-group $rg --namespace-name $evNamespace| grep name |grep twin-change| awk -F "\"" '{print $4}'| cut -d "/" -f1)
      twinchangeEvConn=$(az eventhubs eventhub authorization-rule keys list --resource-group $rg --namespace-name $evNamespace --eventhub-name $twinchangeEv --name $ehQueueAuthRule |grep primaryConnectionString | awk -F "\"" '{print $4}')
      # aks JWT issuer
      aksName=$(az aks list -g $rg | grep name | grep aks | cut -d "/" -f1| awk -F "\"" '{print $4}')
      jwtIssuer="https://$aksName.${{ parameters.location }}.cloudapp.azure.com/auth"
      # app config endpoint
      appConfig=$(az functionapp list --resource-group $rg | grep name | grep appconfig | awk -F "\"" '{print $4}' | head -1)
      appConfigEndpoint="https://$appConfig/api/SetAppConfigKey"
      deviceTwin=$(az functionapp list --resource-group $rg | grep name | grep devicetwin | awk -F "\"" '{print $4}' | tail -1)
      deviceTwinFuncUri="https://$deviceTwin.scm.azurewebsites.net"
      storageAccountKey=$(az storage account keys list -g $ODIN_DEV_RG -n functiondefinition --query [0].value -o tsv)
      # set the keys
      # Import Keys
      az appconfig kv import -y --name ${{ parameters.appConfigName }} --format json --source file --path "$(System.DefaultWorkingDirectory)/deployment/pipelines/templates/infra/app-config-template-translated.json"
      # Set KeyVault Keys
      az appconfig kv set --key Global:ClientAuth:JWT:aadappid --value $servicePrincipalId --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:ClientAuth:JWT:authissuer --value $jwtIssuer --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:AzureActiveDirectory:aadappid --value $servicePrincipalId --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:AzureActiveDirectory:aadappsecret --value $servicePrincipalKey --name ${{ parameters.appConfigName }} --yes
      # Set Environment Info
      az appconfig kv set --key Global:resourceGroup --value ${{ parameters.resourceGroup }} --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:subscriptionId --value $(az account show | jq -r .id) --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:instrumentationKey --value $appInsightKey --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:StorageAccount:Key --value $storageAccountKey --name ${{ parameters.appConfigName }} --yes
      # Set dynamic TMS keys
      az appconfig kv set --key TenantManagerService:cosmosDbEndpoint --value $cosmosDbEndpoint --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:cosmosDbToken --value $cosmosDbAuthKey --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:lifecycleEventHubConnString --value $lifecycleEvConn --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:telemetryEventHubConnString --value $telemetryEvConn --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:twinChangeEventHubConnString --value $twinchangeEvConn --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:setAppConfigEndpoint --value $appConfigEndpoint --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:setAppConfigFunction --value $appConfigEndpoint --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:twinChangeFunctionUri --value $deviceTwinFuncUri --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:telemetryFunctionUri --value $deviceTwinFuncUri --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:lifecycleFunctionUri --value $deviceTwinFuncUri --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:eventHubNamespaceName --value $evNamespace --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:eventHubAccessPolicyKey --value $evAccessPolicyKey --name ${{ parameters.appConfigName }} --yes
    addSpnToEnvironment: true