
parameters:
  serviceConnection: ''
  resourceGroup: ''
  location: ''
  appConfigName: ''
  aksName: ''
  keyVaultName: ''
  storageAccountName: ''
  automationName: ''
  eventHubName: ''

steps:
- task: AzureResourceGroupDeployment@2
  displayName: "Deploy App Configuration"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: ${{ parameters.location }}
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/appconfig.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/appconfig.json'
    overrideParameters: '-appConfigName ${{ parameters.appConfigName }} -location ${{ parameters.location }}'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

- task: AzureCLI@1
  displayName: Create App Config Secret in Kube
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |-
      az aks get-credentials -n ${{ parameters.aksName }} -g ${{ parameters.resourceGroup }}
      appConfigurationConnectionString=$(az appconfig credential list --name ${{ parameters.appConfigName }} -g ${{ parameters.resourceGroup }} | jq -r .[0].connectionString)
      kubectl create secret generic --namespace=default globalsecrets --from-literal=AppConfigurationConnectionString=$appConfigurationConnectionString --dry-run -o yaml | kubectl apply -f -

- task: AzureCLI@1
  displayName: Add Values to App Config
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |-
      # Needed because Azure Devops has a bug in the extension included, normally the extension will handle the flattening --  Andrew Schmidt
      jq --arg delim ':' 'reduce (tostream|select(length==2)) as $i ({};
          .[[$i[0][]|tostring]|join($delim)] = $i[1]
      )' $(System.DefaultWorkingDirectory)/deployment/pipelines/templates/infra/app-config-template.json > $(System.DefaultWorkingDirectory)/deployment/pipelines/templates/infra/app-config-template-translated.json 
      az appconfig kv import --yes --name ${{ parameters.appConfigName }} --format json --source file --path "$(System.DefaultWorkingDirectory)/deployment/pipelines/templates/infra/app-config-template-translated.json"
      az appconfig kv set --key Global:ClientAuth:Jwt:AadAppId --value $servicePrincipalId --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:AzureActiveDirectory:AppId --value $servicePrincipalId --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:AzureActiveDirectory:AppSecret --value $servicePrincipalKey --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:ResourceGroup --value ${{ parameters.resourceGroup }} --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:SubscriptionId --value $(az account show | jq -r .id) --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:StorageAccount:Name --value ${{ parameters.storageAccountName }} --name ${{ parameters.appConfigName }} --yes

    addSpnToEnvironment: true

- task: AzureCLI@1
  displayName: Add Keyvault Name to App Config
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |-
      az appconfig kv set --key Global:KeyVault:Name --value ${{ parameters.keyVaultName }} --name ${{ parameters.appConfigName }} --yes
    addSpnToEnvironment: true

- task: AzureCLI@1
  displayName: Add Values to App Config
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |-
      rg=${{ parameters.resourceGroup }}
      appInsightName=$(az resource list -g $rg --resource-type "Microsoft.Insights/components" --query [].name --output tsv)
      appInsightKey=$(az resource show -g $rg -n $appInsightName --resource-type "Microsoft.Insights/components" --query properties.InstrumentationKey --output tsv)
      cosmosDbAccountName=$(az cosmosdb list --resource-group $rg --query [].name --output tsv)
      cosmosDbEndpoint="https://$cosmosDbAccountName.documents.azure.com:443/"
      cosmosDbAuthKey=$(az cosmosdb keys list --resource-group $rg --name $cosmosDbAccountName --query primaryMasterKey --output tsv)
      cosmosDbConnection="AccountEndpoint=$cosmosDbEndpoint;AccountKey=$cosmosDbAuthKey;"
      eventhubNamespace=${{ parameters.eventHubName }}
      ehQueueAuthRule='iothubroutes'
      lifecycleEv=$(az eventhubs eventhub list --resource-group $rg --namespace-name $eventhubNamespace --query "[?contains(name, 'lifecycle')]".name --output tsv)
      lifecycleEvConn=$(az eventhubs eventhub authorization-rule keys list --resource-group $rg --namespace-name $eventhubNamespace --eventhub-name $lifecycleEv --name $ehQueueAuthRule --query primaryConnectionString --output tsv)
      telemetryEv=$(az eventhubs eventhub list --resource-group $rg --namespace-name $eventhubNamespace --query "[?contains(name, 'telemetry')]".name --output tsv)
      telemetryEvConn=$(az eventhubs eventhub authorization-rule keys list --resource-group $rg --namespace-name $eventhubNamespace --eventhub-name $telemetryEv --name $ehQueueAuthRule --query primaryConnectionString --output tsv)
      twinchangeEv=$(az eventhubs eventhub list --resource-group $rg --namespace-name $eventhubNamespace --query "[?contains(name, 'twin-change')]".name --output tsv)
      twinchangeEvConn=$(az eventhubs eventhub authorization-rule keys list --resource-group $rg --namespace-name $eventhubNamespace --eventhub-name $twinchangeEv --name $ehQueueAuthRule --query primaryConnectionString --output tsv)
      aksName=$(az aks list -g $rg --query [].name --output tsv)
      jwtIssuer="https://$aksName.${{ parameters.location }}.cloudapp.azure.com/auth"
      appConfig=$(az functionapp list --resource-group $rg --query "[?contains(name, 'appconfig')]".name --output tsv)
      appConfigEndpoint="https://$appConfig/api/SetAppConfigKey"
      deviceTwin=$(az functionapp list --resource-group $rg --query "[?contains(name, 'devicetwin')]".name --output tsv)
      deviceTwinFuncUri="https://$deviceTwin.scm.azurewebsites.net"
      # set the keys
      az appconfig kv set --key Global:ClientAuth:Jwt:AuthIssuer --value $jwtIssuer --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:CosmosDb:AccountName --value $cosmosDbAccountName --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:AutomationAccountName --value ${{ parameters.automationName }} --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:LifecycleEventHubConnectionString --value $lifecycleEvConn --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:TelemetryEventHubConnectionString --value $telemetryEvConn --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:TwinChangeEventHubConnectionString --value $twinchangeEvConn --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:SetAppConfigEndpoint --value $appConfigEndpoint --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:SetAppConfigFunction --value $appConfigEndpoint --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:TwinChangeFunctionUri --value $deviceTwinFuncUri --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:TelemetryFunctionUri --value $deviceTwinFuncUri --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:LifecycleFunctionUri --value $deviceTwinFuncUri --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:EventHubNamespaceName --value $eventhubNamespace --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key Global:InstrumentationKey --value $appInsightKey --name ${{ parameters.appConfigName }} --yes
    addSpnToEnvironment: true