
parameters:
  serviceConnection: ''
  resourceGroup: ''
  automationName: ''
  location: ''

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "automation-odin"' ## <-- follow this example

## Nate Oelke --SME 
# Run book code will be update outside of this pipeline

## TODO -- Deploy ARM Resource
- task: AzureResourceGroupDeployment@2
  displayName: "Create the Azure Automation account"
  inputs:
    azureSubscription: '${{ parameters.serviceConnection }}'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{ parameters.resourceGroup }}'
    location: '${{ parameters.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/automationacct.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/automationacct.json'
    overrideParameters: '-automationAccountName ${{ parameters.automationName }} -servicePrincipalClientId $servicePrincipalId -servicePrincipalClientSecret $servicePrincipalKey'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

## TODO -- Store WebHook information in KeyVault
# createIotHubWebHookUrl
# deleteIotHubWebHookUrl