parameters:
  serviceConnection: ''
  resourceGroup: ''
  location: ''
  cosmosDBAccount: ''
  cosmosDBName: 'iot'
  throughput: 400
  collectionName: ''
  
steps:
# create Cosmos db account, database, collection/throughput
- task: AzureResourceGroupDeployment@2
  displayName: "Create Cosmos DB"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: ${{ parameters.location }}
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/cosmosdb.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/cosmosdb.json'
    overrideParameters: '-accountName ${{ parameters.cosmosDBAccount }} -location ${{ parameters.location }} -primaryRegion ${{ parameters.location }} -databaseName ${{ parameters.cosmosDBName }} -throughput ${{ parameters.throughput }} -container1Name ${{ parameters.collectionName }}'
    deploymentMode: 'Incremental'
