
parameters:
  serviceConnection: ''
  resourceGroup: ''
  location: ''
  eventHubName: ''
  storageAccountName: ''
  subscriptionId: ''
  
steps:

## Deploy ARM Resource
- task: AzureResourceGroupDeployment@2
  displayName: "Create Event Hub"
  inputs:
    azureSubscription: '${{ parameters.serviceConnection }}'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{ parameters.resourceGroup }}'
    location: '${{ parameters.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/eventhub.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/eventhub.json'
    overrideParameters: '-namespaceName ${{ parameters.eventHubName }} -resourceGroup ${{ parameters.resourceGroup }} -location ${{ parameters.location }} -storageAccountName ${{ parameters.storageAccountName }} -subscriptionId ${{ parameters.subscriptionId }}'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

## TODO -- Store the SharedAccessKeys in both Appconfig and keyvault (later we are to move to keyvault)
# TenantManagerService:lifecycleEventHubConnString && lifecycleEventHubConnString
# TenantManagerService:telemetryEventHubConnString && telemetryEventHubConnString
# TenantManagerService:twinChangeEventHubConnString && twinChangeEventHubConnString

- task: AzureCLI@1
  displayName: Add Values to App Config
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |-
      evNamespace=$(az eventhubs namespace list --resource-group ${{ parameters.resourceGroup }}| grep name| grep eventhub| cut -d "/" -f1| awk -F "\"" '{print $4}')
      ehQueueAuthRule='iothubroutes'
      lifecycleEv=$(az eventhubs eventhub list --resource-group ${{ parameters.resourceGroup }} --namespace-name $evNamespace| grep name |grep lifecycle| awk -F "\"" '{print $4}'| cut -d "/" -f1)
      lifecycleEvConn=$(az eventhubs eventhub authorization-rule keys list --resource-group $rg --namespace-name $evNamespace --eventhub-name $lifecycleEv --name $ehQueueAuthRule |grep primaryConnectionString | awk -F "\"" '{print $4}')
      telemetryEv=$(az eventhubs eventhub list --resource-group ${{ parameters.resourceGroup }} --namespace-name $evNamespace| grep name |grep telemetry| awk -F "\"" '{print $4}'| cut -d "/" -f1)
      telemetryEvConn=$(az eventhubs eventhub authorization-rule keys list --resource-group $rg --namespace-name $evNamespace --eventhub-name $telemetryEv --name $ehQueueAuthRule |grep primaryConnectionString | awk -F "\"" '{print $4}')
      twinchangeEv=$(az eventhubs eventhub list --resource-group ${{ parameters.resourceGroup }} --namespace-name $evNamespace| grep name |grep twin-change| awk -F "\"" '{print $4}'| cut -d "/" -f1)
      twinchangeEvConn=$(az eventhubs eventhub authorization-rule keys list --resource-group $rg --namespace-name $evNamespace --eventhub-name $twinchangeEv --name $ehQueueAuthRule |grep primaryConnectionString | awk -F "\"" '{print $4}')
      az appconfig kv set --key TenantManagerService:lifecycleEventHubConnString --value $lifecycleEvConn --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:telemetryEventHubConnString --value $telemetryEvConn --name ${{ parameters.appConfigName }} --yes
      az appconfig kv set --key TenantManagerService:twinChangeEventHubConnString --value $twinchangeEvConn --name ${{ parameters.appConfigName }} --yes
    addSpnToEnvironment: true