
parameters:
  serviceConnection: ''
  resourceGroup: ''
  eventHubName: ''
  storageAccountName: ''
  subscriptionId: ''
  
steps:
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'echo "eventhubs-odin-mt-poc"' ## <-- follow this example

## TODO -- Deploy ARM Resource
- task: AzureResourceGroupDeployment@2
  displayName: "Deploy Azure Kubernetes Service"
  inputs:
    azureSubscription: '${{ parameters.serviceConnection }}'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{ parameters.resourceGroup }}'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/eventhub.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/eventhub.json'
    overrideParameters: '-namespaceName ${{ parameters.eventHubName }} -resourceGroup ${{ parameters.resourceGroup }} -storageAccountName ${{ parameters.storageAccountName }} -subscriptionId ${{ parameters.subscriptionId }}'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

## TODO -- Store the SharedAccessKeys in both Appconfig and keyvault (later we are to move to keyvault)
# TenantManagerService:lifecycleEventHubConnString && lifecycleEventHubConnString
# TenantManagerService:telemetryEventHubConnString && telemetryEventHubConnString
# TenantManagerService:twinChangeEventHubConnString && twinChangeEventHubConnString