
parameters:
  serviceConnection: ''
  resourceGroup: ''
  functionApp1Name: ''
  functionApp2Name: ''
  functionApp3Name: ''
  storageAccountName: ''
  location: ''
  
steps:

## Deploy ARM Resource -- Deploy AppConfig controller Function App
- task: AzureResourceGroupDeployment@2
  displayName: "Create Azure function App: AppConfigController"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: '${{ parameters.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/functions.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/functions.json'
    overrideParameters: '-functionAppName ${{ parameters.functionApp3Name }} -storageAccountName ${{ parameters.storageAccountName }} -runtime dotnet'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

## TODO -- Get Trigger binding information CLI probally. Event Hub based
## Deploy ARM Resource
- task: AzureResourceGroupDeployment@2
  displayName: "Create Azure function App: Messaging"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: '${{ parameters.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/functions.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/functions.json'
    overrideParameters: '-functionAppName ${{ parameters.functionApp1Name }} -storageAccountName ${{ parameters.storageAccountName }} -runtime node'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

## Deploy ARM Resource -- Deploy Device Properties Function App (talk to Swami)
## Function has been created with ver 1.0 in Odin env, here both the functions created with ver 2.0
- task: AzureResourceGroupDeployment@2
  displayName: "Create Azure function App: DeviceProperties"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: '${{ parameters.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/functions.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/functions.json'
    overrideParameters: '-functionAppName ${{ parameters.functionApp2Name }} -storageAccountName ${{ parameters.storageAccountName }} -runtime dotnet'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

