
parameters:
  serviceConnection: ''
  resourceGroup: ''
  functionApp1Name: ''
  functionApp2Name: ''
  storageAccountName: ''
  location: ''
  appConfigName: ''
  appInsightsName: ''
  
steps:

## Deploy ARM Resource -- AppConfig controller FunctionApp
- task: AzureResourceGroupDeployment@2
  displayName: "Create Azure function App: AppConfigController"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: '${{ parameters.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/functions.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/functions.json'
    overrideParameters: '-functionAppName ${{ parameters.functionApp2Name }} -appInsightsName ${{ parameters.appInsightsName }} -storageAccountName ${{ parameters.storageAccountName }} -runtime dotnet'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

## Deploy ARM Resource - DeviceTwinFunctionApp 
- task: AzureResourceGroupDeployment@2
  displayName: "Create Azure function App: DeviceTwinFunctionApp"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: '${{ parameters.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/functions.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/functions.json'
    overrideParameters: '-functionAppName ${{ parameters.functionApp1Name }} -appInsightsName ${{ parameters.appInsightsName }} -storageAccountName ${{ parameters.storageAccountName }} -runtime dotnet'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

- task: AzureCLI@1
  displayName: "CLI: set appsettings for fucntion app"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    scriptLocation: 'inlineScript'
    inlineScript: |-
      devicetwinPropfn=${{ parameters.functionApp1Name }}
      kVaultName=${{ parameters.keyVaultName }}
      cosmosDbConn=$(az keyvault secret show --name "documentDBConnectionString" --vault-name $kVaultName | grep value | awk -F '\"' '{print $4}')
      lifecycleEvConn=$(az keyvault secret show --name "lifecycleEventHubConnString" --vault-name $kVaultName | grep value | awk -F '\"' '{print $4}')
      telemetryEvConn=$(az keyvault secret show --name "telemetryEventHubConnString" --vault-name $kVaultName | grep value | awk -F '\"' '{print $4}')
      twinchangeEvConn=$(az keyvault secret show --name "twinChangeEventHubConnString" --vault-name $kVaultName | grep value | awk -F '\"' '{print $4}')
      az functionapp config appsettings set --name $devicetwinPropfn \
        --settings "CosmosDbConnectionString"="$cosmosDbConn" \
          "CosmosDbDatabaseName"="iot" \
          "EventHubTelemetry"="$telemetryEvConn" \
          "ConsumerGroup"="lifecyclecg" \
          "DeviceCG"="messagingfunctions"\
          "DPCacheCG"="dpcache",
          "ConsumerGroupTC"="twinchangecg" \
          "CosmosConnection"="$cosmosDbConn" \
          "CosmosDB"="pcs-storage" \
          "CosmosDBRus"="400" \
          "EventHubLifecycle"="$lifecycleEvConn" \
          "EventHubName"="lifecycle" \
          "EventHubNameTC"="twin-change" \
          "EventHubTwinChange"="$twinchangeEvConn" \
          "WhiteList"="tags.*,reported.*, reported.Protocol, reported.SupportedMethods, reported.DeviceMethodStatus, reported.FirmwareUpdateStatus" \
        --resource-group ${{ parameters.resourceGroup }}
