parameters:
  serviceConnection: ''
  resourceGroup: ''
  keyVaultName: ''
  
steps:
## Create SSH key for IdentityGateway, store in Keyvault
- task: AzureCLI@1
  displayName: "create SSH key"
  inlineScript: |-
     ssh-keygen -b 2048 -t rsa -C "a9my8zz@mmm.com" -f $(System.DefaultWorkingDirectory)/sshkeys -q -N ""
     cat sshkeys > identityGatewayKeys.pem
     ssh-keygen -f sshkeys.pub -e -m pem >> identityGatewayKeys.pem
     ssh-keygen -f sshkeys.pub -e -m pem > identitypub.pem
     az keyvault secret set --vault-name ${{ parameters.keyVaultName }} --name 'identityGatewayPrivateKey' --file $(System.DefaultWorkingDirectory)/identityGatewayKeys.pem
     az keyvault secret set --vault-name ${{ parameters.keyVaultName }} --name 'identityGatewayPublicKey' --file $(System.DefaultWorkingDirectory)/identitypub.pem
  useGlobalConfig: true
