
parameters:
  serviceConnection: ''
  resourceGroup: ''
  mapsName: ''
  location: ''

steps:
## TODO -- Deploy ARM Resource
- task: AzureResourceGroupDeployment@2
  displayName: "Create Azure Maps"
  inputs:
    azureSubscription: '${{ parameters.serviceConnection }}'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '${{ parameters.resourceGroup }}'
    location: '${{ parameters.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/maps.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/maps.json'
    overrideParameters: '-mapsAccountName ${{ parameters.mapsName }}'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

## TODO -- Store the azureMapsKey in keyvault 
# added to keyvault script 