
parameters:
  serviceConnection: ''
  resourceGroup: ''
  storageAccountName: ''
  blobContainer: ''
  location: ''

steps:
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'echo "eventhubs-odin-mt-poc"' ## <-- follow this example

## TODO -- Deploy ARM Resource <updated by Radha>
- task: AzureResourceGroupDeployment@2
  displayName: "Create Azure Storage account"
  inputs:
    azureSubscription: ${{ parameters.serviceConnection }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: '${{ parameters.location }}'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/templates/storageacct.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/deployment/ARM/parameters/storageacct.json'
    overrideParameters: '-storageAccountName ${{ parameters.storageAccountName }} -blobContainerName ${{ parameters.blobContainerName }} -location ${{ parameters.location }}'
    deploymentMode: 'Incremental'
    addSpnToEnvironment: true

## TODO -- Store the storageAccountConnectionString in keyvault 