# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - iothub-manager/**

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: '3M-CRSLAD16-BBIoTP-Dev'
    azureResourceGroup: 'rg-crslbbiot-odin-dev'
    kubernetesCluster: 'aks-dev-spaces-odin'
    namespace: 'default'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'charts/generic-service'
    releaseName: 'iothub-manager'
    recreate: true