apiVersion: v1
kind: Service
metadata:
  name: {{ template "storage-adapter.fullname" . }}-svc
  labels:
    app: {{ template "storage-adapter.name" . }}
    chart: {{ template "storage-adapter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "storage-adapter.name" . }}
    release: {{ .Release.Name }}
