# 
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - storage-adpater/

pool:
  vmImage: 'ubuntu-latest'

steps:
# - task: HelmDeploy@0
#  inputs:
#    connectionType: 'Azure Resource Manager'
#    azureSubscription: '3M-CRSLAD16-BBIoTP-Dev'
#    azureResourceGroup: 'rg-crslbbiot-odin-dev'
#    kubernetesCluster: 'aks-dev-spaces-odin'
#    namespace: 'default'
#    command: 'upgrade'
#    chartType: 'FilePath'
#    chartPath: 'storage-adapter'
#    releaseName: 'iothub-manager'
#    recreate: true
#    tillerNamespace: 'tiller'
    