# 
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - identity-gateway/

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: '3M-CRSLAD16-BBIoTP-Dev-odinarc'
    repository: 'identity-gateway'
    command: 'buildAndPush'
    Dockerfile: 'identity-gateway/Dockerfile'
    buildContext: 'identity-gateway'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: '3M-CRSLAD16-BBIoTP-Dev'
    appName: 'aziotidentitygateway'
    deployToSlotOrASE: true
    resourceGroupName: 'rg-crslbbiot-odin-dev'
    slotName: 'staging'
    containers: 'odinarc.azurecr.io/identity-gateway:$(Build.BuildId)'
- task: AzureAppServiceManage@0
  inputs:
    azureSubscription: '3M-CRSLAD16-BBIoTP-Dev'
    Action: 'Swap Slots'
    WebAppName: 'aziotidentitygateway'
    ResourceGroupName: 'rg-crslbbiot-odin-dev'
    SourceSlot: 'staging'
- task: AzureCLI@1
  inputs:
    azureSubscription: '3M-CRSLAD16-BBIoTP-Dev'
    scriptLocation: 'inlineScript'
    inlineScript: |-
      az aks use-dev-spaces -g rg-crslbbiot-odin-dev -n aks-dev-spaces-odin -s default
      azds up -d
    workingDirectory: 'identity-gateway'
- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'
# - task: HelmDeploy@0
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscription: '3M-CRSLAD16-BBIoTP-Dev'
#     azureResourceGroup: 'rg-crslbbiot-odin-dev'
#     kubernetesCluster: 'aks-dev-spaces-odin'
#     namespace: 'identity'
#     command: 'upgrade'
#     chartType: 'Name'
#     chartName: 'scripts/cd/identity-gateway'
#     releaseName: 'identity-gateway'
# - task: HelmDeploy@0
#  inputs:
#    connectionType: 'Azure Resource Manager'
#    azureSubscription: '3M-CRSLAD16-BBIoTP-Dev'
#    azureResourceGroup: 'rg-crslbbiot-odin-dev'
#    kubernetesCluster: 'aks-dev-spaces-odin'
#    namespace: 'default'
#    command: 'upgrade'
#    chartType: 'FilePath'
#    chartPath: 'storage-adapter'
#    releaseName: 'iothub-manager'
#    recreate: true
#    tillerNamespace: 'tiller'
    