kind: helm-release
apiVersion: 1.1
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/config
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: config
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to form the service's public URL: [space.s.][rootSpace.]config.<random suffix>.<region>.azds.io
      # Customize the public URL by changing the 'config' text between the $(rootSpacePrefix) and $(hostSuffix) tokens
      # For more information see https://aka.ms/devspaces/routing
      - $(spacePrefix)$(rootSpacePrefix)config$(hostSuffix)
    secrets: 
      PCS:
        KEYVAULT_NAME: keyvault-hzgvu 
        AAD_APPID: 95d3c662-23ea-4e2d-8d3d-ea2448706934
        AAD_APPSECRET: YWIwYzhkYjktNjFmZi00MTI5LWE0YjAtNjAyZGNmNWFlNzVk=
    
    service:
      type: ClusterIP
      port: 9005
      targetPort: 9005
configurations:
  develop:
    build:
      useGitIgnore: true