# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master 
  paths:
    include:
    - config/

pr:
  branches:
    include:
    - master
  paths: 
    include:
    - config/

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'OdinDockerHub'
        repository: 'azureiot3m/config'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/config/WebService/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/config'
        tags: |
          $(tag)