
name: IoT Infrastructure

stages:
## CRSL ----
## Currently Pirate Ninja environment. Please dont touch dev. Lets discuss Dev strategy
- stage: DeployCRSLDev
  dependsOn: []
  displayName: Deploy To CRSL Dev
  jobs:
  - template: templates/approval.yaml
    parameters:
      environment: IoT_CRSL_Environment_Dev
  - template: templates/infra.yaml
    parameters:
      serviceConnection: '3M-CRSLAD16-BBIoTP-DEV'
      resourceGroup: rg-iot-crsl-dev
      location: centralus
      environment: IoT_CRSL_Environment_Dev
      subscriptionId: c36fb2f8-f98d-40d0-90a9-d65e93acb428
      applicationCode: crsliot
      deployEnvironment: dev
      platformOperationServiceConnection: '3M-CRSLBL01-CRSL-Digital-Platforms-Bluebird'

## CRSL QA ----
- stage: DeployCRSLQA
  dependsOn:
  - DeployCRSLDev
  displayName: Deploy To CRSL QA
  jobs:
  - template: templates/approval.yaml
    parameters:
      environment: IoT_CRSL_Environment_QA
  - template: templates/infra.yaml
    parameters:
      serviceConnection: '3M-CRSLAD17-BBIoTP-QA'
      resourceGroup: rg-iot-crsl-qa
      location: centralus
      environment: IoT_CRSL_Environment_QA
      subscriptionId: f27c7c03-1ea8-49b8-9878-106e434b8a23
      applicationCode: crsliot
      deployEnvironment: qa
      platformOperationServiceConnection: '3M-CRSLBL01-CRSL-Digital-Platforms-Bluebird'      
      
## CRSL CT ----
# - stage: DeployCRSLCT
#   dependsOn: []
#   #- DeployCRSLDev
#   displayName: Deploy To CRSL CT
#   jobs:
#   - template: templates/approval.yaml
#     parameters:
#       environment: IoT_CRSL_Environment_CT
#   - template: templates/infra.yaml
#     parameters:
#       serviceConnection: '3M-CRSLAD18-BBIoTP-CT'
#       resourceGroup: rg-iot-crsl-ct
#       location: centralus
#       environment: IoT_CRSL_Environment_CT
#       subscriptionId: c6236fd8-0a23-42f3-b997-76d2721591da
#       applicationCode: crsliot
#       deployEnvironment: ct  

## CRSL WKBNCH ----
- stage: DeployCRSLWkBnch
  dependsOn: []
  displayName: Deploy To CRSL WorkBench
  jobs:
  - template: templates/approval.yaml
    parameters:
      environment: IoT_CRSL_Environment_WKBNCH
  - template: templates/infra.yaml
    parameters:
      serviceConnection: '3M-CRSLAD19-BBIoTP-Prod'
      resourceGroup: rg-iot-crsl-wkbnch
      location: centralus
      environment: IoT_CRSL_Environment_WKBNCH
      subscriptionId: dcb37438-95ca-4a68-812d-39ce0d591df2
      applicationCode: crsliot
      deployEnvironment: wkbnch
      platformOperationServiceConnection: '3M-CRSLBL01-CRSL-Digital-Platforms-Bluebird'      
      
- stage: DeployCHIMDev
  dependsOn:
  - DeployCRSLWkBnch
  displayName: Deploy To CHIM Dev
  jobs:
  - template: templates/approval.yaml
    parameters:
      environment: IoT_CHIM_Environment_DEV
  - template: templates/infra.yaml
    parameters:
      serviceConnection: '3M-ACTAIR01-CHIMSMART-Dev'
      resourceGroup: rg-iot-chim-dev
      location: centralus
      environment: IoT_CHIM_Environment_DEV
      subscriptionId: 28299656-8110-4dc4-a33f-82a6cc3d05c2
      applicationCode: chimiot
      deployEnvironment: dev   
      platformOperationServiceConnection: '3M-CRSLBL01-CRSL-Digital-Platforms-Bluebird'

- stage: DeployCHIMQA
  dependsOn: 
  - DeployCRSLWkBnch
  displayName: Deploy To CHIM QA
  jobs:
  - template: templates/approval.yaml
    parameters:
      environment: IoT_CHIM_Environment_QA
  - template: templates/infra.yaml
    parameters:
      serviceConnection: '3M-ACTAIR02-CHIMSMART-QA'
      resourceGroup: rg-iot-chim-qa
      location: centralus
      environment: IoT_CHIM_Environment_QA
      subscriptionId: 30975220-85e1-4769-8bc1-4542ec8569a0
      applicationCode: chimiot
      deployEnvironment: qa  
      platformOperationServiceConnection: '3M-CRSLBL01-CRSL-Digital-Platforms-Bluebird'

# PSD Dev
- stage: DeployPSDDev
  dependsOn: 
  - DeployCRSLWkBnch
  displayName: Deploy To PSD Dev
  jobs:
  - template: templates/approval.yaml
    parameters:
      environment: IoT_PSD_Environment_DEV
  - template: templates/infra.yaml
    parameters:
      serviceConnection: '3M-PSD-Dev'
      resourceGroup: rg-iot-psd-dev
      location: centralus
      subscriptionId: 1d0a4e20-e44d-43b5-97b0-9b577f5bf048
      applicationCode: psdiot
      deployEnvironment: dev
      environment: IoT_PSD_Environment_DEV
      platformOperationServiceConnection: '3M-CRSLBL01-CRSL-Digital-Platforms-Bluebird'
      
- stage: DebugEnv
  dependsOn: []
  displayName: DebugZone
  jobs:
  - job: 
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Bash@3
      displayName: "Get ARG Max"
      inputs:
        targetType: 'inline'
        script: 'getconf ARG_MAX'
        workingDirectory: "$(System.DefaultWorkingDirectory)"
