
name: IoT Infrastructure

stages:
## CRSL ----
- stage: DeployCRSL
  dependsOn: []
  displayName: Deploy To CRSL
  jobs:
  - template: templates/approval.yaml
    parameters:
      environment: IoT_CRSL_Environment
  - template: templates/infra.yaml
    parameters:
      serviceConnection: 81b05a72-5abf-4916-a1b6-4798213d8865
      resourceGroup: rg-pirate-ninja-test1
      location: centralus
      aksName: crsliotaksninja1
      environment: IoT_CRSL_Environment
      subscriptionId: c36fb2f8-f98d-40d0-90a9-d65e93acb428
      applicationCode: crsliot
      deployEnvironment: test
      certThumbprint: D03EDA463EC6A2B2F0C87F2F72347D38B9AAB9AD
      applicationId: 95d3c662-23ea-4e2d-8d3d-ea2448706934
      applicationKey: tog]_*a?hXtzD6Z0TWSm6lyPHKsx7H*F

# PSD
- stage: DeployPSD
  dependsOn: []
  displayName: Deploy To PSD
  jobs:
  - template: templates/approval.yaml
    parameters:
      environment: IoT_PSD_Environment
  - template: templates/infra.yaml
    parameters:
      serviceConnection: 81b05a72-5abf-4916-a1b6-4798213d8865
      resourceGroup: rg-odin-test-deploy-psd
      location: centralus
      aksName: aksTestOdinPSD
      subscriptionId: c36fb2f8-f98d-40d0-90a9-d65e93acb428
      applicationCode: psdiot
      deployEnvironment: dev
      certThumbprint: D03EDA463EC6A2B2F0C87F2F72347D38B9AAB9AD
      applicationId: 95d3c662-23ea-4e2d-8d3d-ea2448706934
      applicationKey: tog]_*a?hXtzD6Z0TWSm6lyPHKsx7H*F

- stage: DebugEnv
  dependsOn: []
  displayName: DebugZone
  jobs:
  - job: 
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Bash@3
      displayName: "Get ARG Max"
      inputs:
        targetType: 'inline'
        script: 'getconf ARG_MAX'
        workingDirectory: "$(System.DefaultWorkingDirectory)"
