pool:
  vmImage: ubuntu-latest

pr:
  - master

trigger:
  - master

schedules:
  - cron: 0 0 * * *
    displayName: Daily midnight build
    branches:
      include:
        - master
    always: true

steps:
  - checkout: none

  - script: |-
      echo "This pipeline serves only to signal other pipelines to run (even if they exist in other repositories)"
    displayName: Signal other pipelines
