pool:
  vmImage: ubuntu-latest

pr:
- master

trigger:
- master

schedules:
- cron: 0 0 * * *
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

steps:
  - script: |-
      echo "This pipeline serves only to trigger other pipelines that may exist in other repositories"
    displayName: Trigger other pipelines