parameters:
  environment: ''

jobs:
- deployment: 
  displayName: Get approval
  pool:
    vmImage: 'ubuntu-16.04'
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'echo "Deployment Approved"'