parameters:
  service: ''

stages:

        
- stage: DeployCRSLDev
  dependsOn: []
  displayName: Deploy To CRSL Dev
  jobs:
  - template: approval.yaml
    parameters:
      environment: IoT_CRSL_Environment_Dev
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: service-deploy.yaml
      parameters:
        serviceConnection: '3M-CRSLAD16-BBIoTP-DEV'
        resourceGroup: rg-crslbbiot-odin-dev
        aksName: aks-dev-spaces-odin
        chartLocation: 'deployment/charts/${{parameters.service}}'
        releaseName: ${{parameters.service}}

- stage: DeployCRSLQA
  dependsOn:
  - DeployCRSLDev
  displayName: Deploy To CRSL QA
  jobs:
  - template: approval.yaml
    parameters:
      environment: IoT_CRSL_Environment_QA
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: service-deploy.yaml
      parameters:
        serviceConnection: '3M-CRSLAD17-BBIoTP-QA'
        resourceGroup: rg-iot-crsl-qa
        aksName: crsliot-aks-qa
        chartLocation: 'deployment/charts/${{parameters.service}}'
        releaseName: ${{parameters.service}}

- stage: DeployCRSLWkBnch
  dependsOn:
  - DeployCRSLQA
  displayName: Deploy To CRSL Work Bench
  jobs:
  - template: approval.yaml
    parameters:
      environment: IoT_CRSL_Environment_WKBNCH
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: service-deploy.yaml
      parameters:
        serviceConnection: '3M-CRSLAD19-BBIoTP-Prod'
        resourceGroup: rg-iot-crsl-wkbnch
        aksName: crsliot-aks-wkbnch
        chartLocation: 'deployment/charts/${{parameters.service}}'
        releaseName: ${{parameters.service}}

- stage: DeployCHIMDev
  dependsOn:
  - DeployCRSLQA
  displayName: Deploy To CHIM Dev
  jobs:
  - template: approval.yaml
    parameters:
      environment: IoT_CHIM_Environment_DEV
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: service-deploy.yaml
      parameters:
        serviceConnection: '3M-ACTAIR01-CHIMSMART-Dev'
        resourceGroup: rg-iot-chim-dev
        aksName: chimiot-aks-dev
        chartLocation: 'deployment/charts/${{parameters.service}}'
        releaseName: ${{parameters.service}}

- stage: DeployCHIMQA
  dependsOn:
  - DeployCRSLQA
  displayName: Deploy To CHIM QA
  jobs:
  - template: approval.yaml
    parameters:
      environment: IoT_CHIM_Environment_QA
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: service-deploy.yaml
      parameters:
        serviceConnection: 'IoT_CHIM_Environment_QA'
        resourceGroup: rg-iot-chim-qa
        aksName: chimiot-aks-qa
        chartLocation: 'deployment/charts/${{parameters.service}}'
        releaseName: ${{parameters.service}}

- stage: DeployPSDDev
  dependsOn:
  - DeployCRSLQA
  displayName: Deploy To PSD Dev
  jobs:
  - template: approval.yaml
    parameters:
      environment: IoT_PSD_Environment_DEV
  - job:
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - template: service-deploy.yaml
      parameters:
        serviceConnection: '3M-PSD-Dev'
        resourceGroup: rg-iot-psd-dev
        aksName: psdiot-aks-dev
        chartLocation: 'deployment/charts/${{parameters.service}}'
        releaseName: ${{parameters.service}}
