# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - tenant-manager/

pr:
  branches:
    include:
    - master
  paths:
    include:
    - tenant-manager/

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/tenant-manager/WebService/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/tenant-manager'
        tags: |
          $(tag)