pr:
  branches:
    include:
    - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  azureSubscription: 3M-CRSLAD16-BBIoTP-Dev
  resourceGroup: rg-crslbbiot-odin-dev
  aksCluster: aks-dev-spaces-odin
  devSpace: pr-$(System.PullRequest.PullRequestNumber)-$(Build.SourceVersion)
  pcsAppConfig: "https://app-config-odin.azconfig.io;Id=0-l4-s0:/avC76+mF2P0dRQdykx0;Secret=/yJ835E0xwCfEPGP36FGp9lPgswgoNVLjeCOfYu34v0="

jobs:
- template: deployment/pipelines/pr/testServiceTemplate.yaml
  parameters:
    service: config

- template: deployment/pipelines/pr/testServiceTemplate.yaml
  parameters:
    service: device-telemetry