parameters:
  service: ''
  azureSubscription: ''
  resourceGroup: ''
  aksCluster: ''
  devSpace: ''

jobs:
- job:
  displayName: Start ${{parameters.service}} Service in Dev Spaces
  pool:
      vmImage: 'ubuntu-latest'
  steps:

#     # Check if this service has been edited in the PR
#   - script: |
#       continue=`git diff origin/master... --name-only | cut -d / -f 1 | grep ${{parameters.service}} -cim1`
#       echo "##vso[task.setvariable variable=continue]$continue"

  - task: AzureCLI@1
    displayName: Azds Up
    # condition: eq(variables['continue'], '1')
    inputs:
      azureSubscription: ${{parameters.azureSubscription}}
      scriptLocation: 'inlineScript'
      inlineScript: |
        az aks use-dev-spaces -g ${{parameters.resourceGroup}} -n ${{parameters.aksCluster}} -s ${{parameters.devSpace}} -y
        cd $(System.DefaultWorkingDirectory)/${{parameters.service}}/WebService
        azds up -d