parameters:
  service: ''
  azureSubscription: ''
  resourceGroup: ''
  aksCluster: ''
  devSpace: ''

jobs:
- job:
  displayName: Test ${{parameters.service}} Service
  pool:
      vmImage: 'ubuntu-latest'
  steps:

#   # Check if this service has been edited in the PR
#   - script: |
#       continue=`git diff origin/master... --name-only | cut -d / -f 1 | grep ${{parameters.service}} -cim1`
#       echo "##vso[task.setvariable variable=continue]$continue"
    
  # This service has been edited so let's test it
  - task: DotNetCoreCLI@2
    displayName: Unit Test
    # condition: eq(variables['continue'], '1')
    inputs:
      command: test
      projects: '${{parameters.service}}/**/*Test.csproj'

  - task: AzureCLI@1
    displayName: Get Service Dev Space URL and Update Env File
    # condition: eq(variables['continue'], '1')
    inputs:
      azureSubscription: ${{parameters.azureSubscription}}
      scriptLocation: 'inlineScript'
      inlineScript: |
        az aks use-dev-spaces -g ${{parameters.resourceGroup}} -n ${{parameters.aksCluster}} -s ${{parameters.devSpace}} -y
        az aks get-credentials -g ${{parameters.resourceGroup}} -n ${{parameters.aksCluster}}
        serviceUri=`azds list-uris -o json | jq -r '.[] | select(.workloadName=="${{parameters.service}}") | .uri'`
        echo $serviceUri
        jq -r --arg serviceUri "$serviceUri" '.values[0].value = $serviceUri' ${{parameters.service}}/WebService.Test/newmanEnvironment.json > tempEnv
        mv tempEnv ${{parameters.service}}/WebService.Test/newmanEnvironment.json
        cat ${{parameters.service}}/WebService.Test/newmanEnvironment.json

  - task: Bash@3
    displayName: Install Newman
    # condition: eq(variables['continue'], '1')
    inputs:
      targetType: 'inline'
      script: |
        sudo npm install newman -g

  - task: NewmanPostman@4
    displayName: Run Postman Integration Tests
    # condition: eq(variables['continue'], '1')
    inputs:
      collectionSourceType: 'file'
      Contents: '${{parameters.service}}/WebService.Test/testCollection.json'
      environment: '${{parameters.service}}/WebService.Test/newmanEnvironment.json'
      reporters: 'cli,junit'
      reporterJUnitExport: $(System.DefaultWorkingDirectory)/${{parameters.service}}-integration-test-report.xml

  - task: PublishTestResults@2
    # condition: eq(variables['continue'], '1')
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/${{parameters.service}}-integration-test-report.xml'