parameters:
  service: ''

jobs:
- job:
  displayName: Test ${{parameters.service}} Service
  pool:
      vmImage: 'ubuntu-latest'
  steps:

  # Check if this service has been edited in the PR
  - script: |
      echo `git diff origin/master... --name-only`
      echo `git diff origin/master... --name-only | cut -d / -f 1`
      continue=`git diff origin/master... --name-only | cut -d / -f 1 | grep $service -cim1`
      echo `parameters.service`
      echo `$service`
      echo `$(service)`
      echo $continue
      echo "##vso[task.setvariable variable=continue]$continue"
    
  # This service has been edited so let's test it
  - task: DotNetCoreCLI@2
    displayName: Unit Test
    condition: and(succeeded(), eq(variables['continue'], '1'))
    inputs:
      command: test
      projects: '${{parameters.service}}/**/*Test.csproj'

  # - task: NewmanPostman@4
  #   displayName: Run Postman Integration Tests
  #   inputs:
  #     collectionSourceType: 'file'
  #     Contents: '${{parameters.service}}/**/WebService.Test/testCollection.json'
  #     environmentSourceType: 'none'
  #     reporters: 'cli,junit'
  #     reporterJUnitExport: $(System.DefaultWorkingDirectory)/${{parameters.service}}-integration-test-report.xml